### ISSUE TITLE
请问搜索接口失效了吗？

### ISSUE THREAD

**Issue by wuchangfeng** [hujiaweibujidao/Ganks-for-gank.io#2]
我用接口测试工具测了一下 search 接口，发现都是 404，但是 workflow 有时候又能返回数据列表。是云平台不稳定的原因吗？另外还想请教一下萧大，你的这个接口数据很干净，是从 Gank 的接口返回的带有 html 元素的 Json 数据中提取出来的吗？还是怎么其他的？

**Comment by hujiaweibujidao** [comment]
嗯，workflow的后台在heroku上，长时间没有访问的时候会暂停服务，每24小时也会暂停几个小时，所以特别不稳定，这个项目是从gank的接口中返回的数据中抽取出来的，这个抽取不仅是获取了干货的标题，还包括干货对应网址的内容，所以搜索更准确些。

anyway，代码家后来对gank.io的搜索接口做了优化，那个搜索接口更加稳定，如果需要使用gank的搜索接口的话，推荐使用代码家的那个搜索接口，我的这个搜索接口也不再更新了 :-)

**Comment by wuchangfeng** [comment]
恩，好的，主要是学习一下 workflow 的开发。感觉接口返回的数据比较清晰点，就方便点，哈哈。

谢谢啦。
